version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpwd
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Uncomment below line to mount initialization scripts
      # - ./init:/docker-entrypoint-initdb.d
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d devdb"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
    name: postgres_dev_data

networks:
  postgres_network:
    name: postgres_dev_network
    driver: bridge
